services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finance_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: finance_api
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data: