services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finance_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: ${ENV}
      DB_HOST: db
      DB_NAME: finance_api
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres: